news/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('', MainView.as_view(), name='main'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('premoderation/', PremoderationView.as_view(), name='premoderation'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('posts/', CreatePostView.as_view(), name='create-post')
]

news_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('news.urls')),
]

news/models/base_model.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class BaseModel(models.Model):
    date_created = models.DateTimeField(_('date created'), auto_now_add=True)
    date_updated = models.DateTimeField(_('date updated'), auto_now=True)

    class Meta:
        abstract = True

news/models/comment.py
from django.db import models
from .base_model import BaseModel
from .post import Post
from .user import User


class Comment(BaseModel):
    to_post = models.ForeignKey(Post, on_delete=models.PROTECT)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    text = models.TextField()

    def __str__(self):
        return f"{self.author} - {self.text}"

news/models/post.py
from django.db import models
from .base_model import BaseModel
from .user import User


class Post(BaseModel):
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    title = models.CharField(max_length=200)
    text = models.TextField()
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.author} - {self.title}"

news/models/user.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from ..managers.user_manager import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    birthdate = models.DateField(_('birth date'), null=True, blank=True)

    is_superuser = models.BooleanField(_('superuser'), default=False)
    is_staff = models.BooleanField(_('staff'), default=False)

    date_created = models.DateTimeField(_('date created'), auto_now_add=True)
    date_updated = models.DateTimeField(_('date updated'), auto_now=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        if self.first_name is '' or self.last_name is '':
            return self.email
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        '''
        Returns the short name for the user.
        '''
        return self.first_name

news/views/base_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from news.library.constants import login_url


class BaseView(LoginRequiredMixin, View):
    login_url = login_url

news/templates/base.html
{% load static %}
{% load groupfilter %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    {% block page_title %}
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog-post.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'main' %}">News site</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Click Me!
                    </a>
                    <div class="dropdown-menu dropdown-menu-right animate slideIn" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'create-post' %}">Make a post</a>
                        {% if request.user|group:"Editor" or request.user|group:"Admin" %}
                        <a class="dropdown-item" href="{% url 'premoderation' %}">Premoderation</a>
                        <a class="dropdown-item" href="{% url 'admin:index' %}">Admin page</a>
                        {% endif %}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

news/templates/create_post.html
{% extends 'base.html' %}
{% block page_title %}
<title>Make post</title>
{% endblock %}

{% block content %}


<h1>Create your post here</h1>
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit" value="Post">Create post</button>
</form>
{% endblock %}

news/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Welcome</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'login_style.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>

</head>

<body>
<div class="container-fluid">
    <div class="row no-gutter">
        <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
        <div class="col-md-8 col-lg-6">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-md-9 col-lg-8 mx-auto">
                            <h3 class="login-heading mb-4">Welcome!</h3>
                            <form method="POST">
                                {% csrf_token %}
                                {{ form }}
                                <div class="custom-control custom-checkbox mb-3">
                                    <input type="checkbox" class="custom-control-input" id="customCheck1">
                                    <label class="custom-control-label" for="customCheck1">Remember password</label>
                                </div>
                                <button
                                        type="submit"
                                        class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2"
                                        value="Login">Sign in
                                </button>
                                <div class="text-center">
                                    <a class="small" href="#">Forgot password?</a></div>
                                <div class="text-center">
                                    <a class="small" href="{% url 'registration' %}">Register</a></div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</body>

</html>

news/templates/main.html
{% extends 'base.html' %}
{% block page_title %}
<title>News</title>
{% endblock %}

{% block content %}
<!-- Page Content -->
<div class="container">

    <div class="row">
        {% for post in posts %}

        <!-- Post Content Column -->
        <div class="col-lg-8">

            <!-- Title -->
            <h1 class="mt-4">{{ post.title }}</h1>

            <!-- Author -->
            <p class="lead">
                by
                <a href="#">{{ post.author.get_full_name }}</a>
            </p>

            <hr>

            <!-- Date/Time -->
            <p>Posted on {{ post.date_created }}</p>

            <hr>

            <!-- Post Content -->
            {{ post.text }}
            <hr>

            <!-- Comments Form -->
            <div class="card my-4">
                <h5 class="card-header">Leave a Comment:</h5>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <textarea class="form-control" rows="3" name="text"></textarea>
                        </div>
                        <input type="hidden" name="to_post" value="{{ post.id }}">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
            {% for comment in post.comment_set.all %}

            <!-- Single Comment -->
            <div class="media mb-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                    <h5 class="mt-0">{{ comment.author.get_full_name }} at {{ comment.date_updated }}</h5>
                    {{ comment.text }}
                </div>
            </div>
            {% endfor %}
<hr>

        </div>

        {% endfor %}

    </div>
</div>
{% endblock %}

news/templates/premoderation.html
{% extends 'base.html' %}
{% block page_title %}
<title>Premoderation</title>
{% endblock %}
{% block content %}

    {% for post in posts %}
    <p>Post {{ forloop.counter }}</p>
    <p>Author: {{ post.author }}</p>
    <p>Text: {{ post.text }}</p>
    <p>Posted: {{ post.is_approved }}</p>
    <p>End post</p>
    <form method="post">
        {% csrf_token %}

        <input type="hidden" name="post_id" value="{{ post.id }}">
        <input type="submit" name="approve" value="Approve">
        <input type="submit" name="decline" value="Decline">

    </form>
    {% endfor %}
{% endblock %}

news/templates/profile.html
{% extends 'base.html' %}
{% block page_title %}
<title>Profile</title>
{% endblock %}

{% block content %}
<p>Profile's page!</p>
{% endblock %}

news/templates/registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

</head>
<body>
<!------ Include the above in your HEAD tag ---------->

<h2>Sign up</h2>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
        {% endfor %}
    </p>
    {% endfor %}
    <button type="submit">Sign up</button>
</form>

</body>
</html>